// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/intake-v1/Plaatsing.tsx": () => import("../components/mockups/intake-v1/Plaatsing.tsx"),
  "./components/mockups/intake-v1/ProgrammaOverzicht.tsx": () => import("../components/mockups/intake-v1/ProgrammaOverzicht.tsx"),
  "./components/mockups/intake-v1/Wizard.tsx": () => import("../components/mockups/intake-v1/Wizard.tsx"),
  "./components/mockups/parent-shell-v1/Dashboard.tsx": () => import("../components/mockups/parent-shell-v1/Dashboard.tsx"),
  "./components/mockups/parent-shell-v1/Diplomas.tsx": () => import("../components/mockups/parent-shell-v1/Diplomas.tsx"),
  "./components/mockups/parent-shell-v1/MijnLessen.tsx": () => import("../components/mockups/parent-shell-v1/MijnLessen.tsx"),
  "./components/mockups/parent-shell-v1/Voortgang.tsx": () => import("../components/mockups/parent-shell-v1/Voortgang.tsx"),
  "./components/mockups/public-shell-v2/Redesign.tsx": () => import("../components/mockups/public-shell-v2/Redesign.tsx"),
  "./components/mockups/trainer-shell-v1/Beoordelen.tsx": () => import("../components/mockups/trainer-shell-v1/Beoordelen.tsx"),
  "./components/mockups/trainer-shell-v1/Berichten.tsx": () => import("../components/mockups/trainer-shell-v1/Berichten.tsx"),
  "./components/mockups/trainer-shell-v1/Dashboard.tsx": () => import("../components/mockups/trainer-shell-v1/Dashboard.tsx"),
  "./components/mockups/trainer-shell-v1/DashboardV2.tsx": () => import("../components/mockups/trainer-shell-v1/DashboardV2.tsx"),
  "./components/mockups/trainer-shell-v1/Documenten.tsx": () => import("../components/mockups/trainer-shell-v1/Documenten.tsx"),
  "./components/mockups/trainer-shell-v1/Groepen.tsx": () => import("../components/mockups/trainer-shell-v1/Groepen.tsx"),
  "./components/mockups/trainer-shell-v1/Leerling.tsx": () => import("../components/mockups/trainer-shell-v1/Leerling.tsx"),
  "./components/mockups/trainer-shell-v1/Taken.tsx": () => import("../components/mockups/trainer-shell-v1/Taken.tsx")
};
