// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/public-shell-v2/Redesign.tsx": () => import("../components/mockups/public-shell-v2/Redesign.tsx"),
  "./components/mockups/trainer-shell-v1/Beoordelen.tsx": () => import("../components/mockups/trainer-shell-v1/Beoordelen.tsx"),
  "./components/mockups/trainer-shell-v1/Dashboard.tsx": () => import("../components/mockups/trainer-shell-v1/Dashboard.tsx")
};
